In [1]:
import numpy as np

In [2]:
List = [45,48,79,80,74]

In [11]:
nparr = np.array(List)

In [4]:
type(nparr)

numpy.ndarray

In [5]:
List1 = range(1000)

In [6]:
nparr = np.array(List1)

In [7]:
%timeit [i**2 for i in List1]

318 µs ± 10.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%timeit nparr**2

1.26 µs ± 30 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
# 1 d array 

In [12]:
nparr

array([45, 48, 79, 80, 74])

In [13]:
nparr.ndim

1

In [15]:
nparr[1]

48

In [16]:
len(nparr)

5

In [17]:
nparr.shape

(5,)

In [18]:
# 2D array 

In [19]:
nparr2 = np.array([[4,5,6,7]])
nparr2

array([[4, 5, 6, 7]])

In [20]:
nparr2.ndim

2

In [21]:
nparr2 = np.array([[4,5,6,7],[7,8,9,10]])
nparr2

array([[ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [22]:
#3D array

In [23]:
nparr2 = np.array([[[4,5,6,7],[7,8,9,10]]])
nparr2.ndim

3

In [24]:
nparr2.shape

(1, 2, 4)

In [26]:
nparr3 = np.array([[[4,5],[6,7],[7,8],[9,10]]])
nparr3

array([[[ 4,  5],
        [ 6,  7],
        [ 7,  8],
        [ 9, 10]]])

In [27]:
nparr3.shape

(1, 4, 2)

In [28]:
nparr4 = np.array(range(0,50))
nparr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [29]:
nparr4.shape

(50,)

In [30]:
nparr4.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
nparr4.reshape(1,5,10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]])

In [32]:
nparr4.reshape(2,5,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [33]:
nparr4.reshape(5,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [35]:
nparr3 = np.mat([1,2,3,4])
nparr3.shape

(1, 4)