# Data Preprocessing

## Importing libraries

In [11]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import StandardScaler

## Adding dataset path & Reading file

In [12]:
path = r'diabetes.csv'

In [13]:
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(path, names = names , header = 0)
array = dataframe.values

## Using StandardScaler

In [14]:
data_scaler = StandardScaler().fit(array)
data_rescaled = data_scaler.transform(array)

In [15]:
set_printoptions(precision=2)
print("\n Standardized data:\n", data_rescaled[0:10])


 Standardized data:
 [[ 0.64  0.85  0.15  0.91 -0.69  0.2   0.47  1.43  1.37]
 [-0.84 -1.12 -0.16  0.53 -0.69 -0.68 -0.37 -0.19 -0.73]
 [ 1.23  1.94 -0.26 -1.29 -0.69 -1.1   0.6  -0.11  1.37]
 [-0.84 -1.   -0.16  0.15  0.12 -0.49 -0.92 -1.04 -0.73]
 [-1.14  0.5  -1.5   0.91  0.77  1.41  5.48 -0.02  1.37]
 [ 0.34 -0.15  0.25 -1.29 -0.69 -0.81 -0.82 -0.28 -0.73]
 [-0.25 -1.34 -0.99  0.72  0.07 -0.13 -0.68 -0.62  1.37]
 [ 1.83 -0.18 -3.57 -1.29 -0.69  0.42 -1.02 -0.36 -0.73]
 [-0.55  2.38  0.05  1.53  4.02 -0.19 -0.95  1.68  1.37]
 [ 1.23  0.13  1.39 -1.29 -0.69 -4.06 -0.72  1.77  1.37]]
